import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import ClientLayout from "./ClientLayout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable} style={{ margin: 0, padding: 0 }}>
        {/* <QueryClientProvider>
          <AuthProvider> */}
        <AntdRegistry>
          <ClientLayout>{children}</ClientLayout>
        </AntdRegistry>
        {/* </AuthProvider>
        </QueryClientProvider> */}
      </body>
    </html>
  );
}
